export const API_V1_ALLOURPARTS_LIST = "API_V1_ALLOURPARTS_LIST"
export const API_V1_ALLOURPARTS_LIST_SUCCEEDED =
  "API_V1_ALLOURPARTS_LIST_SUCCEEDED"
export const API_V1_ALLOURPARTS_LIST_FAILED = "API_V1_ALLOURPARTS_LIST_FAILED"
export const API_V1_ALLOURPARTS_CREATE = "API_V1_ALLOURPARTS_CREATE"
export const API_V1_ALLOURPARTS_CREATE_SUCCEEDED =
  "API_V1_ALLOURPARTS_CREATE_SUCCEEDED"
export const API_V1_ALLOURPARTS_CREATE_FAILED =
  "API_V1_ALLOURPARTS_CREATE_FAILED"
export const API_V1_ALLOURPARTS_READ = "API_V1_ALLOURPARTS_READ"
export const API_V1_ALLOURPARTS_READ_SUCCEEDED =
  "API_V1_ALLOURPARTS_READ_SUCCEEDED"
export const API_V1_ALLOURPARTS_READ_FAILED = "API_V1_ALLOURPARTS_READ_FAILED"
export const API_V1_ALLOURPARTS_UPDATE = "API_V1_ALLOURPARTS_UPDATE"
export const API_V1_ALLOURPARTS_UPDATE_SUCCEEDED =
  "API_V1_ALLOURPARTS_UPDATE_SUCCEEDED"
export const API_V1_ALLOURPARTS_UPDATE_FAILED =
  "API_V1_ALLOURPARTS_UPDATE_FAILED"
export const API_V1_ALLOURPARTS_PARTIAL_UPDATE =
  "API_V1_ALLOURPARTS_PARTIAL_UPDATE"
export const API_V1_ALLOURPARTS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_ALLOURPARTS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_ALLOURPARTS_PARTIAL_UPDATE_FAILED =
  "API_V1_ALLOURPARTS_PARTIAL_UPDATE_FAILED"
export const API_V1_ALLOURPARTS_DELETE = "API_V1_ALLOURPARTS_DELETE"
export const API_V1_ALLOURPARTS_DELETE_SUCCEEDED =
  "API_V1_ALLOURPARTS_DELETE_SUCCEEDED"
export const API_V1_ALLOURPARTS_DELETE_FAILED =
  "API_V1_ALLOURPARTS_DELETE_FAILED"
export const API_V1_CDOCS_LIST = "API_V1_CDOCS_LIST"
export const API_V1_CDOCS_LIST_SUCCEEDED = "API_V1_CDOCS_LIST_SUCCEEDED"
export const API_V1_CDOCS_LIST_FAILED = "API_V1_CDOCS_LIST_FAILED"
export const API_V1_CDOCS_CREATE = "API_V1_CDOCS_CREATE"
export const API_V1_CDOCS_CREATE_SUCCEEDED = "API_V1_CDOCS_CREATE_SUCCEEDED"
export const API_V1_CDOCS_CREATE_FAILED = "API_V1_CDOCS_CREATE_FAILED"
export const API_V1_CDOCS_READ = "API_V1_CDOCS_READ"
export const API_V1_CDOCS_READ_SUCCEEDED = "API_V1_CDOCS_READ_SUCCEEDED"
export const API_V1_CDOCS_READ_FAILED = "API_V1_CDOCS_READ_FAILED"
export const API_V1_CDOCS_UPDATE = "API_V1_CDOCS_UPDATE"
export const API_V1_CDOCS_UPDATE_SUCCEEDED = "API_V1_CDOCS_UPDATE_SUCCEEDED"
export const API_V1_CDOCS_UPDATE_FAILED = "API_V1_CDOCS_UPDATE_FAILED"
export const API_V1_CDOCS_PARTIAL_UPDATE = "API_V1_CDOCS_PARTIAL_UPDATE"
export const API_V1_CDOCS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CDOCS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CDOCS_PARTIAL_UPDATE_FAILED =
  "API_V1_CDOCS_PARTIAL_UPDATE_FAILED"
export const API_V1_CDOCS_DELETE = "API_V1_CDOCS_DELETE"
export const API_V1_CDOCS_DELETE_SUCCEEDED = "API_V1_CDOCS_DELETE_SUCCEEDED"
export const API_V1_CDOCS_DELETE_FAILED = "API_V1_CDOCS_DELETE_FAILED"
export const API_V1_COLUMNS_LIST = "API_V1_COLUMNS_LIST"
export const API_V1_COLUMNS_LIST_SUCCEEDED = "API_V1_COLUMNS_LIST_SUCCEEDED"
export const API_V1_COLUMNS_LIST_FAILED = "API_V1_COLUMNS_LIST_FAILED"
export const API_V1_COLUMNS_CREATE = "API_V1_COLUMNS_CREATE"
export const API_V1_COLUMNS_CREATE_SUCCEEDED = "API_V1_COLUMNS_CREATE_SUCCEEDED"
export const API_V1_COLUMNS_CREATE_FAILED = "API_V1_COLUMNS_CREATE_FAILED"
export const API_V1_COLUMNS_READ = "API_V1_COLUMNS_READ"
export const API_V1_COLUMNS_READ_SUCCEEDED = "API_V1_COLUMNS_READ_SUCCEEDED"
export const API_V1_COLUMNS_READ_FAILED = "API_V1_COLUMNS_READ_FAILED"
export const API_V1_COLUMNS_UPDATE = "API_V1_COLUMNS_UPDATE"
export const API_V1_COLUMNS_UPDATE_SUCCEEDED = "API_V1_COLUMNS_UPDATE_SUCCEEDED"
export const API_V1_COLUMNS_UPDATE_FAILED = "API_V1_COLUMNS_UPDATE_FAILED"
export const API_V1_COLUMNS_PARTIAL_UPDATE = "API_V1_COLUMNS_PARTIAL_UPDATE"
export const API_V1_COLUMNS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_COLUMNS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_COLUMNS_PARTIAL_UPDATE_FAILED =
  "API_V1_COLUMNS_PARTIAL_UPDATE_FAILED"
export const API_V1_COLUMNS_DELETE = "API_V1_COLUMNS_DELETE"
export const API_V1_COLUMNS_DELETE_SUCCEEDED = "API_V1_COLUMNS_DELETE_SUCCEEDED"
export const API_V1_COLUMNS_DELETE_FAILED = "API_V1_COLUMNS_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_JDOCS_LIST = "API_V1_JDOCS_LIST"
export const API_V1_JDOCS_LIST_SUCCEEDED = "API_V1_JDOCS_LIST_SUCCEEDED"
export const API_V1_JDOCS_LIST_FAILED = "API_V1_JDOCS_LIST_FAILED"
export const API_V1_JDOCS_CREATE = "API_V1_JDOCS_CREATE"
export const API_V1_JDOCS_CREATE_SUCCEEDED = "API_V1_JDOCS_CREATE_SUCCEEDED"
export const API_V1_JDOCS_CREATE_FAILED = "API_V1_JDOCS_CREATE_FAILED"
export const API_V1_JDOCS_READ = "API_V1_JDOCS_READ"
export const API_V1_JDOCS_READ_SUCCEEDED = "API_V1_JDOCS_READ_SUCCEEDED"
export const API_V1_JDOCS_READ_FAILED = "API_V1_JDOCS_READ_FAILED"
export const API_V1_JDOCS_UPDATE = "API_V1_JDOCS_UPDATE"
export const API_V1_JDOCS_UPDATE_SUCCEEDED = "API_V1_JDOCS_UPDATE_SUCCEEDED"
export const API_V1_JDOCS_UPDATE_FAILED = "API_V1_JDOCS_UPDATE_FAILED"
export const API_V1_JDOCS_PARTIAL_UPDATE = "API_V1_JDOCS_PARTIAL_UPDATE"
export const API_V1_JDOCS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_JDOCS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_JDOCS_PARTIAL_UPDATE_FAILED =
  "API_V1_JDOCS_PARTIAL_UPDATE_FAILED"
export const API_V1_JDOCS_DELETE = "API_V1_JDOCS_DELETE"
export const API_V1_JDOCS_DELETE_SUCCEEDED = "API_V1_JDOCS_DELETE_SUCCEEDED"
export const API_V1_JDOCS_DELETE_FAILED = "API_V1_JDOCS_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_NOUN_LIST = "API_V1_NOUN_LIST"
export const API_V1_NOUN_LIST_SUCCEEDED = "API_V1_NOUN_LIST_SUCCEEDED"
export const API_V1_NOUN_LIST_FAILED = "API_V1_NOUN_LIST_FAILED"
export const API_V1_NOUN_CREATE = "API_V1_NOUN_CREATE"
export const API_V1_NOUN_CREATE_SUCCEEDED = "API_V1_NOUN_CREATE_SUCCEEDED"
export const API_V1_NOUN_CREATE_FAILED = "API_V1_NOUN_CREATE_FAILED"
export const API_V1_NOUN_READ = "API_V1_NOUN_READ"
export const API_V1_NOUN_READ_SUCCEEDED = "API_V1_NOUN_READ_SUCCEEDED"
export const API_V1_NOUN_READ_FAILED = "API_V1_NOUN_READ_FAILED"
export const API_V1_NOUN_UPDATE = "API_V1_NOUN_UPDATE"
export const API_V1_NOUN_UPDATE_SUCCEEDED = "API_V1_NOUN_UPDATE_SUCCEEDED"
export const API_V1_NOUN_UPDATE_FAILED = "API_V1_NOUN_UPDATE_FAILED"
export const API_V1_NOUN_PARTIAL_UPDATE = "API_V1_NOUN_PARTIAL_UPDATE"
export const API_V1_NOUN_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_NOUN_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_NOUN_PARTIAL_UPDATE_FAILED =
  "API_V1_NOUN_PARTIAL_UPDATE_FAILED"
export const API_V1_NOUN_DELETE = "API_V1_NOUN_DELETE"
export const API_V1_NOUN_DELETE_SUCCEEDED = "API_V1_NOUN_DELETE_SUCCEEDED"
export const API_V1_NOUN_DELETE_FAILED = "API_V1_NOUN_DELETE_FAILED"
export const API_V1_PRODUCTION_LIST = "API_V1_PRODUCTION_LIST"
export const API_V1_PRODUCTION_LIST_SUCCEEDED =
  "API_V1_PRODUCTION_LIST_SUCCEEDED"
export const API_V1_PRODUCTION_LIST_FAILED = "API_V1_PRODUCTION_LIST_FAILED"
export const API_V1_PRODUCTION_CREATE = "API_V1_PRODUCTION_CREATE"
export const API_V1_PRODUCTION_CREATE_SUCCEEDED =
  "API_V1_PRODUCTION_CREATE_SUCCEEDED"
export const API_V1_PRODUCTION_CREATE_FAILED = "API_V1_PRODUCTION_CREATE_FAILED"
export const API_V1_PRODUCTION_READ = "API_V1_PRODUCTION_READ"
export const API_V1_PRODUCTION_READ_SUCCEEDED =
  "API_V1_PRODUCTION_READ_SUCCEEDED"
export const API_V1_PRODUCTION_READ_FAILED = "API_V1_PRODUCTION_READ_FAILED"
export const API_V1_PRODUCTION_UPDATE = "API_V1_PRODUCTION_UPDATE"
export const API_V1_PRODUCTION_UPDATE_SUCCEEDED =
  "API_V1_PRODUCTION_UPDATE_SUCCEEDED"
export const API_V1_PRODUCTION_UPDATE_FAILED = "API_V1_PRODUCTION_UPDATE_FAILED"
export const API_V1_PRODUCTION_PARTIAL_UPDATE =
  "API_V1_PRODUCTION_PARTIAL_UPDATE"
export const API_V1_PRODUCTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PRODUCTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PRODUCTION_PARTIAL_UPDATE_FAILED =
  "API_V1_PRODUCTION_PARTIAL_UPDATE_FAILED"
export const API_V1_PRODUCTION_DELETE = "API_V1_PRODUCTION_DELETE"
export const API_V1_PRODUCTION_DELETE_SUCCEEDED =
  "API_V1_PRODUCTION_DELETE_SUCCEEDED"
export const API_V1_PRODUCTION_DELETE_FAILED = "API_V1_PRODUCTION_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_STATS_LIST = "API_V1_STATS_LIST"
export const API_V1_STATS_LIST_SUCCEEDED = "API_V1_STATS_LIST_SUCCEEDED"
export const API_V1_STATS_LIST_FAILED = "API_V1_STATS_LIST_FAILED"
export const API_V1_STATS_CREATE = "API_V1_STATS_CREATE"
export const API_V1_STATS_CREATE_SUCCEEDED = "API_V1_STATS_CREATE_SUCCEEDED"
export const API_V1_STATS_CREATE_FAILED = "API_V1_STATS_CREATE_FAILED"
export const API_V1_STATS_READ = "API_V1_STATS_READ"
export const API_V1_STATS_READ_SUCCEEDED = "API_V1_STATS_READ_SUCCEEDED"
export const API_V1_STATS_READ_FAILED = "API_V1_STATS_READ_FAILED"
export const API_V1_STATS_UPDATE = "API_V1_STATS_UPDATE"
export const API_V1_STATS_UPDATE_SUCCEEDED = "API_V1_STATS_UPDATE_SUCCEEDED"
export const API_V1_STATS_UPDATE_FAILED = "API_V1_STATS_UPDATE_FAILED"
export const API_V1_STATS_PARTIAL_UPDATE = "API_V1_STATS_PARTIAL_UPDATE"
export const API_V1_STATS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_STATS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_STATS_PARTIAL_UPDATE_FAILED =
  "API_V1_STATS_PARTIAL_UPDATE_FAILED"
export const API_V1_STATS_DELETE = "API_V1_STATS_DELETE"
export const API_V1_STATS_DELETE_SUCCEEDED = "API_V1_STATS_DELETE_SUCCEEDED"
export const API_V1_STATS_DELETE_FAILED = "API_V1_STATS_DELETE_FAILED"
export const API_V1_STATUS_LIST = "API_V1_STATUS_LIST"
export const API_V1_STATUS_LIST_SUCCEEDED = "API_V1_STATUS_LIST_SUCCEEDED"
export const API_V1_STATUS_LIST_FAILED = "API_V1_STATUS_LIST_FAILED"
export const API_V1_STATUS_CREATE = "API_V1_STATUS_CREATE"
export const API_V1_STATUS_CREATE_SUCCEEDED = "API_V1_STATUS_CREATE_SUCCEEDED"
export const API_V1_STATUS_CREATE_FAILED = "API_V1_STATUS_CREATE_FAILED"
export const API_V1_STATUS_READ = "API_V1_STATUS_READ"
export const API_V1_STATUS_READ_SUCCEEDED = "API_V1_STATUS_READ_SUCCEEDED"
export const API_V1_STATUS_READ_FAILED = "API_V1_STATUS_READ_FAILED"
export const API_V1_STATUS_UPDATE = "API_V1_STATUS_UPDATE"
export const API_V1_STATUS_UPDATE_SUCCEEDED = "API_V1_STATUS_UPDATE_SUCCEEDED"
export const API_V1_STATUS_UPDATE_FAILED = "API_V1_STATUS_UPDATE_FAILED"
export const API_V1_STATUS_PARTIAL_UPDATE = "API_V1_STATUS_PARTIAL_UPDATE"
export const API_V1_STATUS_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_STATUS_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_STATUS_PARTIAL_UPDATE_FAILED =
  "API_V1_STATUS_PARTIAL_UPDATE_FAILED"
export const API_V1_STATUS_DELETE = "API_V1_STATUS_DELETE"
export const API_V1_STATUS_DELETE_SUCCEEDED = "API_V1_STATUS_DELETE_SUCCEEDED"
export const API_V1_STATUS_DELETE_FAILED = "API_V1_STATUS_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
