# Generated by Django 2.2.16 on 2020-10-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrostat', '0006_auto_20201030_0129'),
        ('receivingCdocs', '0002_auto_20201030_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdocs',
            name='documentnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdocs_documentnumber', to='hydrostat.Columns'),
        ),
    ]
