# Generated by Django 2.2.16 on 2020-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivingCdocs', '0003_cdocs_documentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdocs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
