# Generated by Django 2.2.16 on 2020-10-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hydrostat", "0004_auto_20201030_0122"),
    ]

    operations = [
        migrations.AddField(
            model_name="columns",
            name="dateIn",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="columns",
            name="dateOut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="columns",
            name="initiateDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
