# Generated by Django 2.2.16 on 2020-10-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrostat', '0009_auto_20201030_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='outgoingserialnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='columns',
            name='sevenLevel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
