# Generated by Django 2.2.16 on 2020-10-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201027_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='incomingserialnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
