# Generated by Django 2.2.16 on 2020-11-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customtext_a10nlguplockact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='incomingserialnumber',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
    ]
