# Generated by Django 2.2.16 on 2020-11-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201101_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='a10slatAct',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
