# Generated by Django 2.2.16 on 2020-10-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hydrostat', '0010_auto_20201030_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOurParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a10brake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allourparts_a10brake', to='hydrostat.Columns')),
            ],
        ),
    ]
