# Generated by Django 2.2.16 on 2020-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_auto_20201104_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="allourparts",
            name="a10actuatorm1m2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="a10emeraccum",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="a10flapact",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="a10swivel521233",
            field=models.URLField(blank=True, null=True),
        ),
    ]
