# Generated by Django 2.2.16 on 2020-11-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0006_auto_20201104_1745"),
    ]

    operations = [
        migrations.AddField(
            model_name="allourparts",
            name="f15canopyact",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15jfsaccum",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15lhmlg",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15nlg",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15rhmlg",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15speedbrakeact",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15speedbrakeswivel",
            field=models.URLField(blank=True, null=True),
        ),
    ]
