# Generated by Django 2.2.16 on 2020-11-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0007_auto_20201104_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="allourparts",
            name="f15mlgact",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15pcreservoir",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allourparts",
            name="f15tailhookact",
            field=models.URLField(blank=True, null=True),
        ),
    ]
