# Generated by Django 2.2.16 on 2020-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_allourparts_f16mainretactblk42'),
    ]

    operations = [
        migrations.AddField(
            model_name='allourparts',
            name='f1630brake',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f1650brake',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16bcv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16cartvlvdash2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16cartvlvdash3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16cartvlvdash6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16commservo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16filterpress31rv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16filterret12rv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16jfshandpump',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16mlgblock25',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16mlgblock42',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16nlgblock25',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16nlgblock42',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16noseret003',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16noseret004',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16noseretact002',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16pdublk25',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16pdublk42',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16resdash6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16resdash7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16resdash8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16staypac',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16steeract',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16swivel801',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16swivel810',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allourparts',
            name='f16swivel811',
            field=models.URLField(blank=True, null=True),
        ),
    ]
